### ISSUE TITLE
Make Youtube channel

### ISSUE THREAD

**Issue by ghost** [NoNamedSelfDriveing/ModuBuru#4]
NoNamed 동아리 유튜브 채널을 만들어 보는건 어떨까요?
임베디드의 장점 중 하나는 실행되는 소프트웨어 뿐만 아니라 실제에서 동작하는 하드웨어가 있다는 것입니다

유튜브 채널에 각 프로젝트 마나 재생목록을 만들고 테스트 영상이나 프로젝트 별 최종 데모 영상을 올리고 동아리 홍보용으로 쓰는것도 좋을 것 같습니다!

마지막으로 힘들겠지만 동아리에서 임베디드 개발과 관련된 강의를 만들어 올릴 수 도 있겠죠

**Comment by MagmaTart** [comment]
저희 프로젝트의 시연 영상을 유기적으로 활용하는 데에 큰 도움이 될 것 같습니다.
드라이브와 메일을 위해 만들어 놓은 NoNamed 범용 구글 계정을 이용해 진행해보도록 하겠습니다.
좋은 의견 감사합니다.
